# Copyright Istio Authors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Override prompt to avoid the annoying "I have no name!" in the default prompt
PS1="build-tools:\w\\$ \[$(tput sgr0)\]"
export PS1

# Tab completion for make that works with monorepos.
# In Codespaces the repo is typically under /workspaces/<repo>.
root="${REPO_ROOT:-}"
if [[ -z "${root}" ]]; then
  if [[ -d /work ]]; then
    root="/work"
  elif [[ -d /workspaces ]]; then
    root="/workspaces"
  else
    root="/"
  fi
fi

make_options=$(find "${root}" -maxdepth 6 -iname "Makefile*" 2>/dev/null | xargs -r -I {} grep -hoE '^[a-zA-Z0-9_.-]+:([^=]|$)' {} | sed 's/[^a-zA-Z0-9_.-]*$//' | sort -u)
complete -W "$make_options" make


