// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// AgentGatewayIntegrationApplyConfiguration represents a declarative configuration of the AgentGatewayIntegration type for use
// with apply.
type AgentGatewayIntegrationApplyConfiguration struct {
	Enabled *bool `json:"enabled,omitempty"`
}

// AgentGatewayIntegrationApplyConfiguration constructs a declarative configuration of the AgentGatewayIntegration type for use with
// apply.
func AgentGatewayIntegration() *AgentGatewayIntegrationApplyConfiguration {
	return &AgentGatewayIntegrationApplyConfiguration{}
}

// WithEnabled sets the Enabled field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Enabled field is set to the value of the last call.
func (b *AgentGatewayIntegrationApplyConfiguration) WithEnabled(value bool) *AgentGatewayIntegrationApplyConfiguration {
	b.Enabled = &value
	return b
}
