// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// DurationFilterApplyConfiguration represents a declarative configuration of the DurationFilter type for use
// with apply.
type DurationFilterApplyConfiguration struct {
	Comparison *ComparisonFilterApplyConfiguration `json:"comparison,omitempty"`
}

// DurationFilterApplyConfiguration constructs a declarative configuration of the DurationFilter type for use with
// apply.
func DurationFilter() *DurationFilterApplyConfiguration {
	return &DurationFilterApplyConfiguration{}
}

// WithComparison sets the Comparison field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Comparison field is set to the value of the last call.
func (b *DurationFilterApplyConfiguration) WithComparison(value *ComparisonFilterApplyConfiguration) *DurationFilterApplyConfiguration {
	b.Comparison = value
	return b
}
