// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HeaderSourceApplyConfiguration represents a declarative configuration of the HeaderSource type for use
// with apply.
type HeaderSourceApplyConfiguration struct {
	Header *string `json:"header,omitempty"`
	Prefix *string `json:"prefix,omitempty"`
}

// HeaderSourceApplyConfiguration constructs a declarative configuration of the HeaderSource type for use with
// apply.
func HeaderSource() *HeaderSourceApplyConfiguration {
	return &HeaderSourceApplyConfiguration{}
}

// WithHeader sets the Header field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Header field is set to the value of the last call.
func (b *HeaderSourceApplyConfiguration) WithHeader(value string) *HeaderSourceApplyConfiguration {
	b.Header = &value
	return b
}

// WithPrefix sets the Prefix field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Prefix field is set to the value of the last call.
func (b *HeaderSourceApplyConfiguration) WithPrefix(value string) *HeaderSourceApplyConfiguration {
	b.Prefix = &value
	return b
}
