// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kgateway-dev/kgateway/api/v1alpha1"
)

// HeaderMatchApplyConfiguration represents a declarative configuration of the HeaderMatch type for use
// with apply.
type HeaderMatchApplyConfiguration struct {
	Key       *string             `json:"key,omitempty"`
	MatchType *v1alpha1.MatchType `json:"matchType,omitempty"`
}

// HeaderMatchApplyConfiguration constructs a declarative configuration of the HeaderMatch type for use with
// apply.
func HeaderMatch() *HeaderMatchApplyConfiguration {
	return &HeaderMatchApplyConfiguration{}
}

// WithKey sets the Key field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Key field is set to the value of the last call.
func (b *HeaderMatchApplyConfiguration) WithKey(value string) *HeaderMatchApplyConfiguration {
	b.Key = &value
	return b
}

// WithMatchType sets the MatchType field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MatchType field is set to the value of the last call.
func (b *HeaderMatchApplyConfiguration) WithMatchType(value v1alpha1.MatchType) *HeaderMatchApplyConfiguration {
	b.MatchType = &value
	return b
}
