// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JWKSApplyConfiguration represents a declarative configuration of the JWKS type for use
// with apply.
type JWKSApplyConfiguration struct {
	LocalJWKS *LocalJWKSApplyConfiguration `json:"local,omitempty"`
}

// JWKSApplyConfiguration constructs a declarative configuration of the JWKS type for use with
// apply.
func JWKS() *JWKSApplyConfiguration {
	return &JWKSApplyConfiguration{}
}

// WithLocalJWKS sets the LocalJWKS field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the LocalJWKS field is set to the value of the last call.
func (b *JWKSApplyConfiguration) WithLocalJWKS(value *LocalJWKSApplyConfiguration) *JWKSApplyConfiguration {
	b.LocalJWKS = value
	return b
}
