// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
)

// JWTClaimMatchApplyConfiguration represents a declarative configuration of the JWTClaimMatch type for use
// with apply.
type JWTClaimMatchApplyConfiguration struct {
	Name    *string                   `json:"name,omitempty"`
	Value   *string                   `json:"value,omitempty"`
	Matcher *apiv1alpha1.ClaimMatcher `json:"matcher,omitempty"`
}

// JWTClaimMatchApplyConfiguration constructs a declarative configuration of the JWTClaimMatch type for use with
// apply.
func JWTClaimMatch() *JWTClaimMatchApplyConfiguration {
	return &JWTClaimMatchApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JWTClaimMatchApplyConfiguration) WithName(value string) *JWTClaimMatchApplyConfiguration {
	b.Name = &value
	return b
}

// WithValue sets the Value field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Value field is set to the value of the last call.
func (b *JWTClaimMatchApplyConfiguration) WithValue(value string) *JWTClaimMatchApplyConfiguration {
	b.Value = &value
	return b
}

// WithMatcher sets the Matcher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Matcher field is set to the value of the last call.
func (b *JWTClaimMatchApplyConfiguration) WithMatcher(value apiv1alpha1.ClaimMatcher) *JWTClaimMatchApplyConfiguration {
	b.Matcher = &value
	return b
}
