// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JWTClaimToHeaderApplyConfiguration represents a declarative configuration of the JWTClaimToHeader type for use
// with apply.
type JWTClaimToHeaderApplyConfiguration struct {
	Name   *string `json:"name,omitempty"`
	Header *string `json:"header,omitempty"`
}

// JWTClaimToHeaderApplyConfiguration constructs a declarative configuration of the JWTClaimToHeader type for use with
// apply.
func JWTClaimToHeader() *JWTClaimToHeaderApplyConfiguration {
	return &JWTClaimToHeaderApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JWTClaimToHeaderApplyConfiguration) WithName(value string) *JWTClaimToHeaderApplyConfiguration {
	b.Name = &value
	return b
}

// WithHeader sets the Header field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Header field is set to the value of the last call.
func (b *JWTClaimToHeaderApplyConfiguration) WithHeader(value string) *JWTClaimToHeaderApplyConfiguration {
	b.Header = &value
	return b
}
