// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JWTTokenSourceApplyConfiguration represents a declarative configuration of the JWTTokenSource type for use
// with apply.
type JWTTokenSourceApplyConfiguration struct {
	Name *string `json:"name,omitempty"`
}

// JWTTokenSourceApplyConfiguration constructs a declarative configuration of the JWTTokenSource type for use with
// apply.
func JWTTokenSource() *JWTTokenSourceApplyConfiguration {
	return &JWTTokenSourceApplyConfiguration{}
}

// WithName sets the Name field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Name field is set to the value of the last call.
func (b *JWTTokenSourceApplyConfiguration) WithName(value string) *JWTTokenSourceApplyConfiguration {
	b.Name = &value
	return b
}
