// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// JWTValidationApplyConfiguration represents a declarative configuration of the JWTValidation type for use
// with apply.
type JWTValidationApplyConfiguration struct {
	ExtensionRef *v1.LocalObjectReference `json:"extensionRef,omitempty"`
}

// JWTValidationApplyConfiguration constructs a declarative configuration of the JWTValidation type for use with
// apply.
func JWTValidation() *JWTValidationApplyConfiguration {
	return &JWTValidationApplyConfiguration{}
}

// WithExtensionRef sets the ExtensionRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the ExtensionRef field is set to the value of the last call.
func (b *JWTValidationApplyConfiguration) WithExtensionRef(value v1.LocalObjectReference) *JWTValidationApplyConfiguration {
	b.ExtensionRef = &value
	return b
}
