// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// JWTValidationApplyConfiguration represents a declarative configuration of the JWTValidation type for use
// with apply.
type JWTValidationApplyConfiguration struct {
	Providers []JWTProviderApplyConfiguration `json:"providers,omitempty"`
}

// JWTValidationApplyConfiguration constructs a declarative configuration of the JWTValidation type for use with
// apply.
func JWTValidation() *JWTValidationApplyConfiguration {
	return &JWTValidationApplyConfiguration{}
}

// WithProviders adds the given value to the Providers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Providers field.
func (b *JWTValidationApplyConfiguration) WithProviders(values ...*JWTProviderApplyConfiguration) *JWTValidationApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithProviders")
		}
		b.Providers = append(b.Providers, *values[i])
	}
	return b
}
