// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/api/core/v1"
)

// LocalJWKSApplyConfiguration represents a declarative configuration of the LocalJWKS type for use
// with apply.
type LocalJWKSApplyConfiguration struct {
	File      *string                  `json:"file,omitempty"`
	InlineKey *string                  `json:"key,omitempty"`
	SecretRef *v1.LocalObjectReference `json:"secretRef,omitempty"`
}

// LocalJWKSApplyConfiguration constructs a declarative configuration of the LocalJWKS type for use with
// apply.
func LocalJWKS() *LocalJWKSApplyConfiguration {
	return &LocalJWKSApplyConfiguration{}
}

// WithFile sets the File field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the File field is set to the value of the last call.
func (b *LocalJWKSApplyConfiguration) WithFile(value string) *LocalJWKSApplyConfiguration {
	b.File = &value
	return b
}

// WithInlineKey sets the InlineKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the InlineKey field is set to the value of the last call.
func (b *LocalJWKSApplyConfiguration) WithInlineKey(value string) *LocalJWKSApplyConfiguration {
	b.InlineKey = &value
	return b
}

// WithSecretRef sets the SecretRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the SecretRef field is set to the value of the last call.
func (b *LocalJWKSApplyConfiguration) WithSecretRef(value v1.LocalObjectReference) *LocalJWKSApplyConfiguration {
	b.SecretRef = &value
	return b
}
