// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RemoteJWKSApplyConfiguration represents a declarative configuration of the RemoteJWKS type for use
// with apply.
type RemoteJWKSApplyConfiguration struct {
	TargetRef *LocalPolicyTargetReferenceApplyConfiguration `json:"targetRefs,omitempty"`
	URL       *string                                       `json:"url,omitempty"`
}

// RemoteJWKSApplyConfiguration constructs a declarative configuration of the RemoteJWKS type for use with
// apply.
func RemoteJWKS() *RemoteJWKSApplyConfiguration {
	return &RemoteJWKSApplyConfiguration{}
}

// WithTargetRef sets the TargetRef field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the TargetRef field is set to the value of the last call.
func (b *RemoteJWKSApplyConfiguration) WithTargetRef(value *LocalPolicyTargetReferenceApplyConfiguration) *RemoteJWKSApplyConfiguration {
	b.TargetRef = value
	return b
}

// WithURL sets the URL field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the URL field is set to the value of the last call.
func (b *RemoteJWKSApplyConfiguration) WithURL(value string) *RemoteJWKSApplyConfiguration {
	b.URL = &value
	return b
}
