// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RuntimeUInt32ApplyConfiguration represents a declarative configuration of the RuntimeUInt32 type for use
// with apply.
type RuntimeUInt32ApplyConfiguration struct {
	DefaultValue *uint32 `json:"defaultValue,omitempty"`
	RuntimeKey   *string `json:"runtimeKey,omitempty"`
}

// RuntimeUInt32ApplyConfiguration constructs a declarative configuration of the RuntimeUInt32 type for use with
// apply.
func RuntimeUInt32() *RuntimeUInt32ApplyConfiguration {
	return &RuntimeUInt32ApplyConfiguration{}
}

// WithDefaultValue sets the DefaultValue field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultValue field is set to the value of the last call.
func (b *RuntimeUInt32ApplyConfiguration) WithDefaultValue(value uint32) *RuntimeUInt32ApplyConfiguration {
	b.DefaultValue = &value
	return b
}

// WithRuntimeKey sets the RuntimeKey field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the RuntimeKey field is set to the value of the last call.
func (b *RuntimeUInt32ApplyConfiguration) WithRuntimeKey(value string) *RuntimeUInt32ApplyConfiguration {
	b.RuntimeKey = &value
	return b
}
