// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	gentype "k8s.io/client-go/gentype"

	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	v1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	typedapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/typed/api/v1alpha1"
)

// fakeJWTValidationPolicies implements JWTValidationPolicyInterface
type fakeJWTValidationPolicies struct {
	*gentype.FakeClientWithListAndApply[*v1alpha1.JWTValidationPolicy, *v1alpha1.JWTValidationPolicyList, *apiv1alpha1.JWTValidationPolicyApplyConfiguration]
	Fake *FakeGatewayV1alpha1
}

func newFakeJWTValidationPolicies(fake *FakeGatewayV1alpha1, namespace string) typedapiv1alpha1.JWTValidationPolicyInterface {
	return &fakeJWTValidationPolicies{
		gentype.NewFakeClientWithListAndApply[*v1alpha1.JWTValidationPolicy, *v1alpha1.JWTValidationPolicyList, *apiv1alpha1.JWTValidationPolicyApplyConfiguration](
			fake.Fake,
			namespace,
			v1alpha1.SchemeGroupVersion.WithResource("jwtvalidationpolicies"),
			v1alpha1.SchemeGroupVersion.WithKind("JWTValidationPolicy"),
			func() *v1alpha1.JWTValidationPolicy { return &v1alpha1.JWTValidationPolicy{} },
			func() *v1alpha1.JWTValidationPolicyList { return &v1alpha1.JWTValidationPolicyList{} },
			func(dst, src *v1alpha1.JWTValidationPolicyList) { dst.ListMeta = src.ListMeta },
			func(list *v1alpha1.JWTValidationPolicyList) []*v1alpha1.JWTValidationPolicy {
				return gentype.ToPointerSlice(list.Items)
			},
			func(list *v1alpha1.JWTValidationPolicyList, items []*v1alpha1.JWTValidationPolicy) {
				list.Items = gentype.FromPointerSlice(items)
			},
		),
		fake,
	}
}
