// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
)

// JWTAuthorizationPoliciesGetter has a method to return a JWTAuthorizationPolicyInterface.
// A group's client should implement this interface.
type JWTAuthorizationPoliciesGetter interface {
	JWTAuthorizationPolicies(namespace string) JWTAuthorizationPolicyInterface
}

// JWTAuthorizationPolicyInterface has methods to work with JWTAuthorizationPolicy resources.
type JWTAuthorizationPolicyInterface interface {
	Create(ctx context.Context, jWTAuthorizationPolicy *apiv1alpha1.JWTAuthorizationPolicy, opts v1.CreateOptions) (*apiv1alpha1.JWTAuthorizationPolicy, error)
	Update(ctx context.Context, jWTAuthorizationPolicy *apiv1alpha1.JWTAuthorizationPolicy, opts v1.UpdateOptions) (*apiv1alpha1.JWTAuthorizationPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, jWTAuthorizationPolicy *apiv1alpha1.JWTAuthorizationPolicy, opts v1.UpdateOptions) (*apiv1alpha1.JWTAuthorizationPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.JWTAuthorizationPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.JWTAuthorizationPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.JWTAuthorizationPolicy, err error)
	Apply(ctx context.Context, jWTAuthorizationPolicy *applyconfigurationapiv1alpha1.JWTAuthorizationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.JWTAuthorizationPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, jWTAuthorizationPolicy *applyconfigurationapiv1alpha1.JWTAuthorizationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.JWTAuthorizationPolicy, err error)
	JWTAuthorizationPolicyExpansion
}

// jWTAuthorizationPolicies implements JWTAuthorizationPolicyInterface
type jWTAuthorizationPolicies struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.JWTAuthorizationPolicy, *apiv1alpha1.JWTAuthorizationPolicyList, *applyconfigurationapiv1alpha1.JWTAuthorizationPolicyApplyConfiguration]
}

// newJWTAuthorizationPolicies returns a JWTAuthorizationPolicies
func newJWTAuthorizationPolicies(c *GatewayV1alpha1Client, namespace string) *jWTAuthorizationPolicies {
	return &jWTAuthorizationPolicies{
		gentype.NewClientWithListAndApply[*apiv1alpha1.JWTAuthorizationPolicy, *apiv1alpha1.JWTAuthorizationPolicyList, *applyconfigurationapiv1alpha1.JWTAuthorizationPolicyApplyConfiguration](
			"jwtauthorizationpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.JWTAuthorizationPolicy { return &apiv1alpha1.JWTAuthorizationPolicy{} },
			func() *apiv1alpha1.JWTAuthorizationPolicyList { return &apiv1alpha1.JWTAuthorizationPolicyList{} },
		),
	}
}
