// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	applyconfigurationapiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/applyconfiguration/api/v1alpha1"
	apiv1alpha1 "github.com/kgateway-dev/kgateway/v2/api/v1alpha1"
	scheme "github.com/kgateway-dev/kgateway/v2/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
)

// JWTValidationPoliciesGetter has a method to return a JWTValidationPolicyInterface.
// A group's client should implement this interface.
type JWTValidationPoliciesGetter interface {
	JWTValidationPolicies(namespace string) JWTValidationPolicyInterface
}

// JWTValidationPolicyInterface has methods to work with JWTValidationPolicy resources.
type JWTValidationPolicyInterface interface {
	Create(ctx context.Context, jWTValidationPolicy *apiv1alpha1.JWTValidationPolicy, opts v1.CreateOptions) (*apiv1alpha1.JWTValidationPolicy, error)
	Update(ctx context.Context, jWTValidationPolicy *apiv1alpha1.JWTValidationPolicy, opts v1.UpdateOptions) (*apiv1alpha1.JWTValidationPolicy, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, jWTValidationPolicy *apiv1alpha1.JWTValidationPolicy, opts v1.UpdateOptions) (*apiv1alpha1.JWTValidationPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*apiv1alpha1.JWTValidationPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*apiv1alpha1.JWTValidationPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *apiv1alpha1.JWTValidationPolicy, err error)
	Apply(ctx context.Context, jWTValidationPolicy *applyconfigurationapiv1alpha1.JWTValidationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.JWTValidationPolicy, err error)
	// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
	ApplyStatus(ctx context.Context, jWTValidationPolicy *applyconfigurationapiv1alpha1.JWTValidationPolicyApplyConfiguration, opts v1.ApplyOptions) (result *apiv1alpha1.JWTValidationPolicy, err error)
	JWTValidationPolicyExpansion
}

// jWTValidationPolicies implements JWTValidationPolicyInterface
type jWTValidationPolicies struct {
	*gentype.ClientWithListAndApply[*apiv1alpha1.JWTValidationPolicy, *apiv1alpha1.JWTValidationPolicyList, *applyconfigurationapiv1alpha1.JWTValidationPolicyApplyConfiguration]
}

// newJWTValidationPolicies returns a JWTValidationPolicies
func newJWTValidationPolicies(c *GatewayV1alpha1Client, namespace string) *jWTValidationPolicies {
	return &jWTValidationPolicies{
		gentype.NewClientWithListAndApply[*apiv1alpha1.JWTValidationPolicy, *apiv1alpha1.JWTValidationPolicyList, *applyconfigurationapiv1alpha1.JWTValidationPolicyApplyConfiguration](
			"jwtvalidationpolicies",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *apiv1alpha1.JWTValidationPolicy { return &apiv1alpha1.JWTValidationPolicy{} },
			func() *apiv1alpha1.JWTValidationPolicyList { return &apiv1alpha1.JWTValidationPolicyList{} },
		),
	}
}
