# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: solo_io/solo_kit/api/v1/ref.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from extproto import ext_pb2 as extproto_dot_ext__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n!solo_io/solo_kit/api/v1/ref.proto\x12\x0c\x63ore.solo.io\x1a\x12\x65xtproto/ext.proto\".\n\x0bResourceRef\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\tBCZ5github.com/solo-io/solo-kit/pkg/api/v1/resources/core\xb8\xf5\x04\x01\xc0\xf5\x04\x01\xd0\xf5\x04\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'solo_io.solo_kit.api.v1.ref_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z5github.com/solo-io/solo-kit/pkg/api/v1/resources/core\270\365\004\001\300\365\004\001\320\365\004\001'
  _globals['_RESOURCEREF']._serialized_start=71
  _globals['_RESOURCEREF']._serialized_end=117
# @@protoc_insertion_point(module_scope)
